import type { ViewItem } from "./ViewItem";
import { sameArrayBy, samePrimitiveArray } from "utils/arrayEquality";

export interface StableViewItemReconcilerOptions<T> {
	getKey: (item: T, index: number) => string;
	toViewItem: (item: T) => ViewItem;
	canReuseSource?: (previousSource: T, nextSource: T) => boolean;
}

export interface StableViewItemReconciler<T> {
	/**
	 * Reconciles an immutable source-array snapshot.
	 * Passing the same array reference again returns the previous result directly.
	 */
	reconcile(items: readonly T[]): ViewItem[];

	/**
	 * Returns the keys generated by the latest reconciliation.
	 */
	getKeys(): readonly string[];

	clear(): void;
}

interface StableViewItemEntry<T> {
	source: T;
	viewItem: ViewItem;
}

function canReuseEntrySource<T>(
	options: StableViewItemReconcilerOptions<T>,
	previousSource: T,
	nextSource: T,
): boolean {
	return options.canReuseSource
		? options.canReuseSource(previousSource, nextSource)
		: previousSource === nextSource;
}

function takeReusableEntry<T>(
	entries: StableViewItemEntry<T>[] | undefined,
	item: T,
	options: StableViewItemReconcilerOptions<T>,
): StableViewItemEntry<T> | undefined {
	if (!entries || entries.length === 0) {
		return undefined;
	}

	for (let index = 0; index < entries.length; index += 1) {
		const candidate = entries[index];
		if (!canReuseEntrySource(options, candidate.source, item)) {
			continue;
		}

		for (
			let shiftIndex = index + 1;
			shiftIndex < entries.length;
			shiftIndex += 1
		) {
			entries[shiftIndex - 1] = entries[shiftIndex];
		}
		entries.pop();
		return candidate;
	}

	return undefined;
}

const hasSameReference = <T>(current: T, next: T): boolean =>
	current === next;

const hasSameArrayContents = (
	nextKeys: readonly string[],
	nextItems: readonly ViewItem[],
	previousKeys: readonly string[],
	previousItems: readonly ViewItem[],
): boolean =>
	samePrimitiveArray(nextKeys, previousKeys) &&
	sameArrayBy(nextItems, previousItems, hasSameReference);

const isViewItem = (item: unknown): item is ViewItem =>
	typeof item === "object" &&
	item !== null &&
	"type" in item &&
	"data" in item;

function refreshViewItemData<T>(
	previousViewItem: ViewItem,
	previousSource: T,
	nextSource: T,
	options: StableViewItemReconcilerOptions<T>,
): ViewItem {
	if (previousSource === nextSource) {
		return previousViewItem;
	}

	if (isViewItem(nextSource)) {
		return previousViewItem;
	}

	const nextViewItem = options.toViewItem(nextSource);
	if (nextViewItem.type !== previousViewItem.type) {
		return nextViewItem;
	}

	(previousViewItem as { data: unknown }).data = nextViewItem.data;
	return previousViewItem;
}

export function createStableViewItemReconciler<T>(
	options: StableViewItemReconcilerOptions<T>,
): StableViewItemReconciler<T> {
	let previousEntriesByBaseKey = new Map<string, StableViewItemEntry<T>[]>();
	let previousArray: ViewItem[] = [];
	let previousKeys: string[] = [];
	let previousSourceArray: readonly T[] | undefined;

	return {
		reconcile(items) {
			if (items === previousSourceArray) {
				return previousArray;
			}

			const nextEntriesByBaseKey = new Map<string, StableViewItemEntry<T>[]>();
			const nextArray = new Array<ViewItem>(items.length);
			const nextKeys = new Array<string>(items.length);

			for (let index = 0; index < items.length; index += 1) {
				const item = items[index];
				const baseKey = options.getKey(item, index);
				const previousEntry = takeReusableEntry(
					previousEntriesByBaseKey.get(baseKey),
					item,
					options,
				);
				const baseViewItem =
					previousEntry
						? refreshViewItemData(
								previousEntry.viewItem,
								previousEntry.source,
								item,
								options,
							)
						: options.toViewItem(item);
				const nextEntriesForKey =
					nextEntriesByBaseKey.get(baseKey) ?? [];

				nextKeys[index] = baseKey;
				nextArray[index] = baseViewItem;
				if (previousEntry) {
					previousEntry.source = item;
					previousEntry.viewItem = baseViewItem;
					nextEntriesForKey.push(previousEntry);
				} else {
					nextEntriesForKey.push({
						source: item,
						viewItem: baseViewItem,
					});
				}
				if (!nextEntriesByBaseKey.has(baseKey)) {
					nextEntriesByBaseKey.set(baseKey, nextEntriesForKey);
				}
			}

			const result = hasSameArrayContents(
				nextKeys,
				nextArray,
				previousKeys,
				previousArray,
			)
				? previousArray
				: nextArray;

			previousEntriesByBaseKey = nextEntriesByBaseKey;
			previousKeys = nextKeys;
			previousArray = result;
			previousSourceArray = items;

			return result;
		},
		getKeys() {
			return previousKeys;
		},
		clear() {
			previousEntriesByBaseKey = new Map();
			previousArray = [];
			previousKeys = [];
			previousSourceArray = undefined;
		},
	};
}
