import type { ViewItem } from "./ViewItem";
import { sameArrayBy, samePrimitiveArray } from "utils/arrayEquality";

export interface StableViewItemReconcilerOptions<T> {
	getKey: (item: T, index: number) => string;
	toViewItem: (item: T) => ViewItem;
	canReuseSource?: (previousSource: T, nextSource: T) => boolean;
}

export interface StableViewItemReconciler<T> {
	/**
	 * Reconciles an immutable source-array snapshot.
	 * Passing the same array reference again returns the previous result directly.
	 */
	reconcile(items: readonly T[]): ViewItem[];

	/**
	 * Returns the keys generated by the latest reconciliation.
	 */
	getKeys(): readonly string[];

	clear(): void;
}

interface StableViewItemEntry<T> {
	source: T;
	viewItem: ViewItem;
}

type EntryBucket<T> = StableViewItemEntry<T> | StableViewItemEntry<T>[];

function canReuseEntrySource<T>(
	options: StableViewItemReconcilerOptions<T>,
	previousSource: T,
	nextSource: T,
): boolean {
	return options.canReuseSource
		? options.canReuseSource(previousSource, nextSource)
		: previousSource === nextSource;
}

function takeReusableEntry<T>(
	bucket: EntryBucket<T> | undefined,
	item: T,
	options: StableViewItemReconcilerOptions<T>,
): { entry: StableViewItemEntry<T>; consumed: boolean } | undefined {
	if (bucket === undefined) {
		return undefined;
	}

	if (Array.isArray(bucket)) {
		if (bucket.length === 0) {
			return undefined;
		}

		for (let index = 0; index < bucket.length; index += 1) {
			const candidate = bucket[index];
			if (!canReuseEntrySource(options, candidate.source, item)) {
				continue;
			}

			for (
				let shiftIndex = index + 1;
				shiftIndex < bucket.length;
				shiftIndex += 1
			) {
				bucket[shiftIndex - 1] = bucket[shiftIndex];
			}
			bucket.pop();
			return { entry: candidate, consumed: bucket.length === 0 };
		}

		return undefined;
	}

	if (canReuseEntrySource(options, bucket.source, item)) {
		return { entry: bucket, consumed: true };
	}

	return undefined;
}

const hasSameReference = <T>(current: T, next: T): boolean => current === next;

const hasSameArrayContents = (
	nextKeys: readonly string[],
	nextItems: readonly ViewItem[],
	previousKeys: readonly string[],
	previousItems: readonly ViewItem[],
): boolean =>
	samePrimitiveArray(nextKeys, previousKeys) &&
	sameArrayBy(nextItems, previousItems, hasSameReference);

const isViewItem = (item: unknown): item is ViewItem =>
	typeof item === "object" && item !== null && "type" in item && "data" in item;

function refreshViewItemData<T>(
	previousViewItem: ViewItem,
	previousSource: T,
	nextSource: T,
	options: StableViewItemReconcilerOptions<T>,
): ViewItem {
	if (previousSource === nextSource) {
		return previousViewItem;
	}

	if (isViewItem(nextSource)) {
		return previousViewItem;
	}

	const nextViewItem = options.toViewItem(nextSource);
	if (nextViewItem.type !== previousViewItem.type) {
		return nextViewItem;
	}

	(previousViewItem as { data: unknown }).data = nextViewItem.data;
	return previousViewItem;
}

export function createStableViewItemReconciler<T>(
	options: StableViewItemReconcilerOptions<T>,
): StableViewItemReconciler<T> {
	let previousEntriesByBaseKey = new Map<string, EntryBucket<T>>();
	let previousArray: ViewItem[] = [];
	let previousKeys: string[] = [];
	let previousSourceArray: readonly T[] | undefined;

	return {
		reconcile(items) {
			if (items === previousSourceArray) {
				return previousArray;
			}

			const nextEntriesByBaseKey = new Map<string, EntryBucket<T>>();
			const nextArray = new Array<ViewItem>(items.length);
			const nextKeys = new Array<string>(items.length);

			for (let index = 0; index < items.length; index += 1) {
				const item = items[index];
				const baseKey = options.getKey(item, index);
				const reusable = takeReusableEntry(
					previousEntriesByBaseKey.get(baseKey),
					item,
					options,
				);
				const previousEntry = reusable?.entry;
				const baseViewItem = previousEntry
					? refreshViewItemData(
							previousEntry.viewItem,
							previousEntry.source,
							item,
							options,
						)
					: options.toViewItem(item);

				nextKeys[index] = baseKey;
				nextArray[index] = baseViewItem;

				const entry: StableViewItemEntry<T> = previousEntry
					? ((previousEntry.source = item),
						(previousEntry.viewItem = baseViewItem),
						previousEntry)
					: { source: item, viewItem: baseViewItem };

				const existingBucket = nextEntriesByBaseKey.get(baseKey);
				if (existingBucket === undefined) {
					nextEntriesByBaseKey.set(baseKey, entry);
				} else if (Array.isArray(existingBucket)) {
					existingBucket.push(entry);
				} else {
					nextEntriesByBaseKey.set(baseKey, [existingBucket, entry]);
				}
			}

			const result = hasSameArrayContents(
				nextKeys,
				nextArray,
				previousKeys,
				previousArray,
			)
				? previousArray
				: nextArray;

			previousEntriesByBaseKey = nextEntriesByBaseKey;
			previousKeys = nextKeys;
			previousArray = result;
			previousSourceArray = items;

			return result;
		},
		getKeys() {
			return previousKeys;
		},
		clear() {
			previousEntriesByBaseKey = new Map();
			previousArray = [];
			previousKeys = [];
			previousSourceArray = undefined;
		},
	};
}
