import type { ViewItem } from "./ViewItem";
import { sameArrayBy, samePrimitiveArray } from "shared/collections/arrayEquality";

export interface StableViewItemReconcilerOptions<T> {
	getKey: (item: T, index: number) => string;
	toViewItem: (item: T) => ViewItem;
	canReuseSource?: (previousSource: T, nextSource: T) => boolean;
}

export interface StableViewItemReconciler<T> {
	/**
	 * Reconciles an immutable source-array snapshot.
	 * Passing the same array reference again returns the previous result directly.
	 */
	reconcile(items: readonly T[]): ViewItem[];

	/**
	 * Returns the keys generated by the latest reconciliation.
	 */
	getKeys(): readonly string[];

	clear(): void;
}

interface StableViewItemEntry<T> {
	source: T;
	viewItem: ViewItem;
	seenGeneration: number;
}

type EntryBucket<T> = StableViewItemEntry<T> | StableViewItemEntry<T>[];

const PENDING_NEW_ENTRY = Symbol("pending-new-entry");

function canReuseEntrySource<T>(
	options: StableViewItemReconcilerOptions<T>,
	previousSource: T,
	nextSource: T,
): boolean {
	return options.canReuseSource
		? options.canReuseSource(previousSource, nextSource)
		: previousSource === nextSource;
}

function takeReusableEntry<T>(
	bucket: EntryBucket<T> | undefined,
	item: T,
	options: StableViewItemReconcilerOptions<T>,
): { entry: StableViewItemEntry<T>; consumed: boolean } | undefined {
	if (bucket === undefined) {
		return undefined;
	}

	if (Array.isArray(bucket)) {
		if (bucket.length === 0) {
			return undefined;
		}

		for (let index = 0; index < bucket.length; index += 1) {
			const candidate = bucket[index];
			if (!canReuseEntrySource(options, candidate.source, item)) {
				continue;
			}

			for (
				let shiftIndex = index + 1;
				shiftIndex < bucket.length;
				shiftIndex += 1
			) {
				bucket[shiftIndex - 1] = bucket[shiftIndex];
			}
			bucket.pop();
			return { entry: candidate, consumed: bucket.length === 0 };
		}

		return undefined;
	}

	if (canReuseEntrySource(options, bucket.source, item)) {
		return { entry: bucket, consumed: true };
	}

	return undefined;
}

const hasSameReference = <T>(current: T, next: T): boolean => current === next;

const hasSameArrayContents = (
	nextKeys: readonly string[],
	nextItems: readonly ViewItem[],
	previousKeys: readonly string[],
	previousItems: readonly ViewItem[],
): boolean =>
	samePrimitiveArray(nextKeys, previousKeys) &&
	sameArrayBy(nextItems, previousItems, hasSameReference);

const isViewItem = (item: unknown): item is ViewItem =>
	typeof item === "object" && item !== null && "type" in item && "data" in item;

function refreshViewItemData<T>(
	previousViewItem: ViewItem,
	previousSource: T,
	nextSource: T,
	options: StableViewItemReconcilerOptions<T>,
): ViewItem {
	if (previousSource === nextSource) {
		return previousViewItem;
	}

	if (isViewItem(nextSource)) {
		return previousViewItem;
	}

	const nextViewItem = options.toViewItem(nextSource);
	if (nextViewItem.type !== previousViewItem.type) {
		return nextViewItem;
	}

	(previousViewItem as { data: unknown }).data = nextViewItem.data;
	return previousViewItem;
}

export function createStableViewItemReconciler<T>(
	options: StableViewItemReconcilerOptions<T>,
): StableViewItemReconciler<T> {
	let previousEntriesByBaseKey = new Map<
		string,
		EntryBucket<T> | typeof PENDING_NEW_ENTRY
	>();
	let previousArray: ViewItem[] = [];
	let previousKeys: string[] = [];
	let previousSourceArray: readonly T[] | undefined;
	let hasDuplicateKeys = false;
	let seenGeneration = 0;

	const reconcileWithDuplicateBuckets = (items: readonly T[]): ViewItem[] => {
		const nextEntriesByBaseKey = new Map<string, EntryBucket<T>>();
		const nextArray = new Array<ViewItem>(items.length);
		const nextKeys = new Array<string>(items.length);
		let nextHasDuplicateKeys = false;

		for (let index = 0; index < items.length; index += 1) {
			const item = items[index];
			const baseKey = options.getKey(item, index);
			const previousBucket = previousEntriesByBaseKey.get(baseKey);
			const reusable =
				previousBucket === PENDING_NEW_ENTRY
					? undefined
					: takeReusableEntry(previousBucket, item, options);
			const previousEntry = reusable?.entry;
			const baseViewItem = previousEntry
				? refreshViewItemData(
						previousEntry.viewItem,
						previousEntry.source,
						item,
						options,
					)
				: options.toViewItem(item);

			nextKeys[index] = baseKey;
			nextArray[index] = baseViewItem;

			const entry: StableViewItemEntry<T> = previousEntry
				? ((previousEntry.source = item),
					(previousEntry.viewItem = baseViewItem),
					previousEntry)
				: { source: item, viewItem: baseViewItem, seenGeneration: 0 };

			const existingBucket = nextEntriesByBaseKey.get(baseKey);
			if (existingBucket === undefined) {
				nextEntriesByBaseKey.set(baseKey, entry);
			} else if (Array.isArray(existingBucket)) {
				nextHasDuplicateKeys = true;
				existingBucket.push(entry);
			} else {
				nextHasDuplicateKeys = true;
				nextEntriesByBaseKey.set(baseKey, [existingBucket, entry]);
			}
		}

		const result = hasSameArrayContents(
			nextKeys,
			nextArray,
			previousKeys,
			previousArray,
		)
			? previousArray
			: nextArray;

		previousEntriesByBaseKey = nextEntriesByBaseKey;
		previousKeys = nextKeys;
		previousArray = result;
		previousSourceArray = items;
		hasDuplicateKeys = nextHasDuplicateKeys;

		return result;
	};

	return {
		reconcile(items) {
			if (items === previousSourceArray) {
				return previousArray;
			}

			if (hasDuplicateKeys) {
				return reconcileWithDuplicateBuckets(items);
			}

			const nextArray = new Array<ViewItem>(items.length);
			const nextKeys = new Array<string>(items.length);
			const generation = seenGeneration + 1;
			seenGeneration = generation;

			for (let index = 0; index < items.length; index += 1) {
				const item = items[index];
				const baseKey = options.getKey(item, index);
				const previousBucket = previousEntriesByBaseKey.get(baseKey);
				if (
					previousBucket === PENDING_NEW_ENTRY ||
					Array.isArray(previousBucket) ||
					previousBucket?.seenGeneration === generation
				) {
					return reconcileWithDuplicateBuckets(items);
				}

				const previousEntry = previousBucket;
				const baseViewItem = previousEntry
					? canReuseEntrySource(options, previousEntry.source, item)
						? refreshViewItemData(
								previousEntry.viewItem,
								previousEntry.source,
								item,
								options,
							)
						: options.toViewItem(item)
					: options.toViewItem(item);

				nextKeys[index] = baseKey;
				nextArray[index] = baseViewItem;
				if (previousEntry) {
					previousEntry.seenGeneration = generation;
				} else {
					previousEntriesByBaseKey.set(baseKey, PENDING_NEW_ENTRY);
				}
			}

			const result = hasSameArrayContents(
				nextKeys,
				nextArray,
				previousKeys,
				previousArray,
			)
				? previousArray
				: nextArray;

			for (const [baseKey, entry] of previousEntriesByBaseKey) {
				if (entry === PENDING_NEW_ENTRY) continue;
				if (Array.isArray(entry) || entry.seenGeneration !== generation) {
					previousEntriesByBaseKey.delete(baseKey);
				}
			}
			for (let index = 0; index < items.length; index += 1) {
				const item = items[index];
				const baseKey = nextKeys[index];
				const viewItem = nextArray[index];
				const entry = previousEntriesByBaseKey.get(baseKey);
				if (entry === PENDING_NEW_ENTRY || entry === undefined) {
					previousEntriesByBaseKey.set(baseKey, {
						source: item,
						viewItem,
						seenGeneration: generation,
					});
					continue;
				}
				if (Array.isArray(entry)) continue;
				entry.source = item;
				entry.viewItem = viewItem;
			}
			previousKeys = nextKeys;
			previousArray = result;
			previousSourceArray = items;
			hasDuplicateKeys = false;

			return result;
		},
		getKeys() {
			return previousKeys;
		},
		clear() {
			previousEntriesByBaseKey = new Map();
			previousArray = [];
			previousKeys = [];
			previousSourceArray = undefined;
			hasDuplicateKeys = false;
		},
	};
}
