import builtins from "builtin-modules";
import esbuild from "esbuild";
import esbuildSvelte from "esbuild-svelte";
import process from "process";
import { sveltePreprocess } from "svelte-preprocess";
import inlineWorkerPlugin from "esbuild-plugin-inline-worker";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const mode = process.argv[2];
const prod = mode === "production";
const profile = mode === "profile";
const optimized = prod || profile;

function readBooleanEnv(name) {
	return process.env[name] === "true" || process.env[name] === "1";
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	plugins: [
		inlineWorkerPlugin(),
		esbuildSvelte({
			compilerOptions: {
				css: "injected",
				dev: !optimized,
			},
			preprocess: sveltePreprocess(),
		}),
	],
	format: "cjs",
	target: "es2018",
	define: {
		"process.env.NODE_ENV": JSON.stringify(
			optimized ? "production" : "development",
		),
		"process.env.CCL_DISABLE_CARD_DOM_PREVIEW": JSON.stringify(
			readBooleanEnv("CCL_DISABLE_CARD_DOM_PREVIEW") ? "true" : "false",
		),
		"process.env.CCL_DISABLE_RENDERED_PREVIEW_CACHE": JSON.stringify(
			readBooleanEnv("CCL_DISABLE_RENDERED_PREVIEW_CACHE") ? "true" : "false",
		),
	},
	logLevel: "info",
	sourcemap: profile ? "inline" : prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (optimized) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
