import builtins from "builtin-modules";
import esbuild from "esbuild";
import esbuildSvelte from "esbuild-svelte";
import process from "process";
import { sveltePreprocess } from "svelte-preprocess";
import inlineWorkerPlugin from "esbuild-plugin-inline-worker";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const mode = process.argv[2] ?? "development";
const prod = mode === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	plugins: [
		inlineWorkerPlugin(),
		esbuildSvelte({
			compilerOptions: {
				css: "injected",
				dev: !prod,
			},
			preprocess: sveltePreprocess(),
		}),
	],
	format: "cjs",
	target: "es2018",
	define: {
		"process.env.NODE_ENV": JSON.stringify(prod ? "production" : "development"),
	},
	logLevel: "info",
	sourcemap: mode === "development" ? "inline" : false,
	treeShaking: true,
	outfile: "main.js",
	minify: mode === "production",
});

if (mode !== "development") {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
