import { parsePositiveInteger, parseTrimmedString } from "./settingDefinition";
import type { SettingDefinition } from "./settingDefinition";

export const DISPLAY_SETTING_DEFINITIONS: ReadonlyArray<SettingDefinition> = [
	{
		section: "language",
		settingKey: "language",
		controlType: "dropdown",
		translationKey: "language",
		descriptionKey: "languageDesc",
		immediate: true,
		options: [
			{ value: "en", label: "English" },
			{ value: "ja", label: "日本語" },
		],
	},
	{
		section: "display",
		settingKey: "displayMode",
		controlType: "dropdown",
		translationKey: "displayMode",
		descriptionKey: "displayModeDesc",
		options: [
			{
				value: "editor-inline",
				label: "belowEditor",
				isTranslationKey: true,
			},
			{ value: "sidebar-view", label: "sidebar", isTranslationKey: true },
			{ value: "hybrid", label: "hybrid", isTranslationKey: true },
		],
	},
	{
		section: "display",
		settingKey: "defaultVisibleLinkCount",
		controlType: "text",
		translationKey: "defaultVisibleLinkCount",
		descriptionKey: "defaultVisibleLinkCountDesc",
		parse: (value) => parsePositiveInteger(value),
		format: (value) => String(value ?? ""),
	},
	{
		section: "display",
		settingKey: "loadMoreLinkIncrement",
		controlType: "text",
		translationKey: "loadMoreLinkIncrement",
		descriptionKey: "loadMoreLinkIncrementDesc",
		parse: (value) => parsePositiveInteger(value),
		format: (value) => String(value ?? ""),
	},
	{
		section: "display",
		settingKey: "sectionMarginBottomPx",
		controlType: "text",
		translationKey: "sectionMarginBottom",
		descriptionKey: "sectionMarginBottomDesc",
		placeholder: "45",
		parse: (value) => parsePositiveInteger(value),
		format: (value) => String(value ?? ""),
	},
	{
		section: "display",
		settingKey: "useMergedLinksSection",
		controlType: "toggle",
		translationKey: "mergeBacklinkOutgoing",
		descriptionKey: "mergeBacklinkOutgoingDesc",
		immediate: true,
	},
	{
		section: "display",
		settingKey: "twoHopHeaderSortOrder",
		controlType: "dropdown",
		translationKey: "twoHopHeaderSortOrder",
		descriptionKey: "twoHopHeaderSortOrderDesc",
		options: [
			{ value: "appearance", label: "appearance", isTranslationKey: true },
			{
				value: "hop2-count-asc",
				label: "linkCountAscending",
				isTranslationKey: true,
			},
		],
	},
	{
		section: "display",
		settingKey: "dedupeCards",
		controlType: "toggle",
		translationKey: "hideDuplicateNotes",
		descriptionKey: "hideDuplicateNotesDesc",
	},
	{
		section: "tags",
		settingKey: "enableTagFeatures",
		controlType: "toggle",
		translationKey: "enableTagFeatures",
		descriptionKey: "enableTagFeaturesDesc",
	},
	{
		section: "tags",
		settingKey: "showTagsSection",
		controlType: "toggle",
		translationKey: "showTagsSection",
		descriptionKey: "showTagsSectionDesc",
	},
	{
		section: "display",
		settingKey: "excludeAttachments",
		controlType: "toggle",
		translationKey: "hideAttachments",
		descriptionKey: "hideAttachmentsDesc",
	},
	{
		section: "canvas",
		settingKey: "showTwoHopForSelectedCanvasFileNode",
		controlType: "toggle",
		translationKey: "followSelectedCanvasFileNode",
		descriptionKey: "followSelectedCanvasFileNodeDesc",
	},
	{
		section: "display",
		settingKey: "enableUnresolvedLinkDecoration",
		controlType: "toggle",
		translationKey: "highlightUnresolvedLinks",
		descriptionKey: "highlightUnresolvedLinksDesc",
	},
	{
		section: "tags",
		settingKey: "enableGlobalSearchTagModal",
		controlType: "toggle",
		translationKey: "openTagSearchDedicatedView",
		descriptionKey: "openTagSearchDedicatedViewDesc",
	},
	{
		section: "emptyViewAllNotes",
		settingKey: "enableEmptyViewAllNotesInNewTab",
		controlType: "toggle",
		translationKey: "showAllNotesNewTab",
		descriptionKey: "showAllNotesNewTabDesc",
	},
	{
		section: "emptyViewAllNotes",
		settingKey: "pinBookmarkedToTopInAllNotes",
		controlType: "toggle",
		translationKey: "pinBookmarkedToTopInAllNotes",
		descriptionKey: "pinBookmarkedToTopInAllNotesDesc",
	},
	{
		section: "dateSortingSettings",
		settingKey: "frontmatterKeyCreatedDate",
		controlType: "text",
		translationKey: "frontmatterKeyCreationDate",
		descriptionKey: "frontmatterKeyCreationDateDesc",
		placeholder: "created",
		parse: (value) => parseTrimmedString(value),
		format: (value) => (typeof value === "string" ? value : ""),
	},
	{
		section: "dateSortingSettings",
		settingKey: "frontmatterKeyModifiedDate",
		controlType: "text",
		translationKey: "frontmatterKeyModificationDate",
		descriptionKey: "frontmatterKeyModificationDateDesc",
		placeholder: "updated",
		parse: (value) => parseTrimmedString(value),
		format: (value) => (typeof value === "string" ? value : ""),
	},
];
