import {
	parseNonNegativeInteger,
	parsePositiveInteger,
	parsePositiveNumber,
	parseTrimmedString,
} from "./settingDefinition";
import type { SettingDefinition } from "./settingDefinition";

export const PREVIEW_SETTING_DEFINITIONS: ReadonlyArray<SettingDefinition> = [
	{
		section: "preview",
		settingKey: "cardWidthPx",
		controlType: "text",
		translationKey: "cardWidth",
		descriptionKey: "cardWidthDesc",
		placeholder: "140",
		parse: (value) => parsePositiveInteger(value),
		format: (value) => String(value ?? ""),
	},
	{
		section: "preview",
		settingKey: "cardHeightRatio",
		controlType: "text",
		translationKey: "cardHeightRatio",
		descriptionKey: "cardHeightRatioDesc",
		placeholder: "1.1",
		parse: (value) => parsePositiveNumber(value),
		format: (value) => String(value ?? ""),
	},
	{
		section: "preview",
		settingKey: "previewMaxLines",
		controlType: "text",
		translationKey: "maximumPreviewLines",
		descriptionKey: "maximumPreviewLinesDesc",
		placeholder: "15",
		parse: (value) => parseNonNegativeInteger(value),
		format: (value) => String(value ?? ""),
	},
	{
		section: "preview",
		settingKey: "previewMaxChars",
		controlType: "text",
		translationKey: "maximumPreviewChars",
		descriptionKey: "maximumPreviewCharsDesc",
		placeholder: "500",
		parse: (value) => parseNonNegativeInteger(value),
		format: (value) => String(value ?? ""),
	},
	{
		section: "preview",
		settingKey: "previewVisualLineSafetyMargin",
		controlType: "text",
		translationKey: "previewVisualLineSafetyMargin",
		descriptionKey: "previewVisualLineSafetyMarginDesc",
		placeholder: "0",
		parse: (value) => parseNonNegativeInteger(value),
		format: (value) => String(value ?? ""),
	},
	{
		section: "preview",
		settingKey: "cardGapPx",
		controlType: "text",
		translationKey: "cardGap",
		descriptionKey: "cardGapDesc",
		placeholder: "12",
		parse: (value) => parseNonNegativeInteger(value),
		format: (value) => String(value ?? ""),
	},
	{
		section: "preview",
		settingKey: "cardMaxColumns",
		controlType: "text",
		translationKey: "cardMaxColumns",
		descriptionKey: "cardMaxColumnsDesc",
		placeholder: "6",
		parse: (value) => parsePositiveInteger(value),
		format: (value) => String(value ?? ""),
	},
	{
		section: "preview",
		settingKey: "priorityFrontmatterKeyForPreview",
		controlType: "text",
		translationKey: "priorityFrontmatterKeyForPreview",
		descriptionKey: "priorityFrontmatterKeyForPreviewDesc",
		placeholder: "description, summary",
		parse: (value) => parseTrimmedString(value),
		format: (value) => (typeof value === "string" ? value : ""),
	},
	{
		section: "preview",
		settingKey: "priorityFrontmatterKeyForTitle",
		controlType: "text",
		translationKey: "priorityFrontmatterKeyForTitle",
		descriptionKey: "priorityFrontmatterKeyForTitleDesc",
		placeholder: "title, name",
		parse: (value) => parseTrimmedString(value),
		format: (value) => (typeof value === "string" ? value : ""),
	},
];
